spring.application.name=stratos

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/stratos_db
spring.datasource.username=stratos_user
spring.datasource.password=stratos_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT Configuration
# Secret key (should be complex and hidden in prod). Using a random large string for dev.
stratos.app.jwtSecret=4D6250655368566D597133743677397A24432646294A404E635266556A586E32
stratos.app.jwtExpirationMs=86400000
